# Generated by Django 6.0.2 on 2026-03-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usersecurity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersecurity',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
    ]
